### ISSUE TITLE
como posso criar fake api com json-server ./src/services server.json ?

### ISSUE THREAD

**Issue by DevCleverton** [rocketseat-education/nlw-05-react-native#2]
Inicie a fake api com json-server ./src/services server.json --host 192.168.1.4 --port 3333 --delay 700. 

Substitua o host pelo seu endereço IP local. Faça o mesmo no arquivo API dentro de services.

**Comment by igor-silva** [comment]
Estou com esse erro:

PS C:\Users\Igor Silva\Documents\nlw\plantmanager> json-server ./src/services server.json --host 192.168.1.102 --port 3333

  \{^_^}/ hi!

  Loading ./src/services
Error: Unsupported source ./src/services
    at C:\Users\Igor Silva\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:79:13
    at new Promise (<anonymous>)
    at module.exports (C:\Users\Igor Silva\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:38:10)
    at start (C:\Users\Igor Silva\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:112:12)
    at module.exports (C:\Users\Igor Silva\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:149:3)
    at module.exports (C:\Users\Igor Silva\AppData\Roaming\npm\node_modules\json-server\lib\cli\index.js:86:3)
    at Object.<anonymous> (C:\Users\Igor Silva\AppData\Roaming\npm\node_modules\json-server\lib\cli\bin.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
PS C:\Users\Igor Silva\Documents\nlw\plantmanager>
